@startuml

Sheet *--> "*" Note
Sheet *--> Tempo
Sheet *--> "*" Beat
Note *--> Duration
Note  *--> "play at" Beat
Duration *--> "*" "Beat"
Beat *--> Frame
Tempo --> Duration 

Note <|-- Silence
Note <|-- Sound

@enduml